metadata:
  title: КОНФИГУРАЦИОННОЕ УПРАВЛЕНИЕ
  subtitle: Учебное пособие
  author: П.Н. Советов
  date: Москва – 2021
  toc-title: Оглавление
  bibliography: bibliography.bib
  link-citations: true
  csl: gost-r-7-0-5-2008-numeric-iaa.csl
